name: Qodana

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          submodules: true

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.1.0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true
